contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nanogenvar channel"
    url: https://nfcore.slack.com/channels/nanogenvar
    about: Discussion about the nf-core/nanogenvar pipeline
